server:
  port: 9000

spring:
  application:
    name: gbh_mm
  mail:
    username: <gmail 계정명>

  security:
    user:
      name: user
      password: 1234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://<DB 주소>:3306/<데이터베이스 명>
    username: root
    password: <DB 비밀번호>
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: off
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: <Redis 서버 주소>
      port: 6379

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
  api-docs:
    path: /v3/api-docs

ssafy:
  api-key: <SSAFY 금융망 API KEY>
google:
  client-id: <구글 API 발급 받은 Client Id>
  client-secret: <구글 API 발급 받은 Client Secret>
  refreshToken: <구글 API 발급 받은 Refresh Token>
  project-id: <프로젝트 명>
  pub sub-topic: <구글 API 발급 받은 Pub Sub Topic>

# JWT setting
jwt:
  salt: <JWT 인코딩 전용 키>
  access-token-expiration: <Access Token 만료 시간>
  refresh-token-expiration: <RefreshToken Token 만료 시간>
share-link-key: <16byte 키>

firebase:
  service:
    account:
      path: <Firebase json 파일 경로>

aws:
  access-key-id: <S3 IM ID>
  secret-access-key: <S3 IM Access Key>
  s3:
    bucket-name: <S3 버킷 명>
    region: <S3 주소>

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always


rsa:
  pubkey: <RSA 공개키>